version: "3"
services:
  backend:
    build: ./src
    container_name: backend
    env_file:
      - ./src/.env
  frontend:
    build: ./public_html/carlos-personal-site
    ports:
      - "22:00"
      - "443:443"
    volumes:
      - ./production.conf:/etc/nginx/conf.d/default.conf
      - ./public_html:/usr/share/nginx/html
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/pwp/etc/letsencrypt/live/cp3develops.com/fullchain.pem:/etc/letsencrypt/live/cp3develops.com/fullchain.pem
      - /docker-volumes/pwp/etc/letsencrypt/live/cp3develops.com/privkey.pem:/etc/letsencrypt/live/cp3develops.com/privkey.pem